version: '3.8'
services:
  tomcat:
    container_name: tomcat
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./target/help-service.war:/usr/local/tomcat/webapps/help-service.war
    deploy:
      restart_policy:
        condition: on-failure
        delay: 3s
        max_attempts: 5
        window: 60s